added new postinstall script

diff --git a/installation_scripts/postinstall b/installation_scripts/postinstall
--- a/installation_scripts/postinstall
+++ b/installation_scripts/postinstall
@@ -1,58 +1,92 @@
 #!/bin/bash
+# Universal Mailer post install scripts. Adapdted from GPGTools
+# https://github.com/GPGTools/GPGMail/blob/dev/Installer/postinstall.sh
 
-# update supported plugin compatibility list
-uuid1=$(cat /Applications/Mail.app/Contents/Info.plist | grep UUID -A 1 | sed -n "s/.*<string>\(.*\)<\/string>/\1/p")
- 
-ed "$2/Contents/Info.plist" <<EOF
-/SupportedPluginCompatibilityUUIDs/
-+
-a
-    <string>$uuid1</string>
-.
-,wq
-EOF
+sysdir="/Library/Mail/Bundles"
+netdir="/Network/Library/Mail/Bundles"
+homedir="$HOME/Library/Mail/Bundles"
+bundle="UniversalMailer.mailbundle"
+USER=${USER:-$(id -un)}
+temporarydir=/tmp/UM-installation-tmp
 
-# move bundle into place
-mkdir -p ~/Library/Mail/Bundles
-rm -R ~/Library/Mail/Bundles/UniversalMailer.mailbundle
-echo "rm -R ~/Library/Mail/Bundles/UniversalMailer.mailbundle"
-mv "$2" ~/Library/Mail/Bundles
- 
-# enable plugin bundles for Mail.app
-if [ `whoami` == root ] ; then
-	echo "is root" > /tmp/installer.um.log
-    domain=/Library/Preferences/com.apple.mail
+
+# Find real target #############################################################
+existingInstallationAt=""
+
+if [[ -e "$netdir/$bundle" ]]; then
+    existingInstallationAt="$netdir"
+    target="$netdir"
+elif [[ -e "$homedir/$bundle" ]]; then
+    existingInstallationAt="$homedir"
+    target="$homedir"
+elif [[ -e "$sysdir/$bundle" ]]; then
+    existingInstallationAt="$sysdir"
+    target="$sysdir"
 else
-	echo "is not root" > /tmp/installer.um.log
-    domain=com.apple.mail
+    target="$sysdir"
 fi
 
-macosx_minor_version=$(sw_vers | /usr/bin/sed -Ene 's/.*[[:space:]]10\.([0-9][0-9]*)\.*[0-9]*/\1/p;')
-if [[ "$macosx_minor_version" == "" ]]; then
-    echo 'Unrecognized Mac OS X version!' > /dev/stderr
-    echo 'Unrecognized Mac OS X version!' >> /tmp/installer.um.log
-    sw_vers > /dev/stderr
+################################################################################
+
+echo "Temporary dir: $temporarydir"
+echo "existing installation at: $existingInstallationAt"
+echo "installation target: $target"
+
+# Check if UniversalMailer is correctly installed ########################################
+if [[ ! -e "$temporarydir/$bundle" ]]; then
+	echo "[universal_mailer] Couldn't install '$bundle' in temporary directory $temporarydir.  Aborting." >&2
+	exit 1
+fi
+################################################################################
+
+# Cleanup ######################################################################
+if [[ "$existingInstallationAt" != "" ]]; then
+    echo "[universal_mailer] Removing existing installation of the bundle..."
+    rm -rf "$existingInstallationAt/$bundle" || exit 1
+fi
+################################################################################
+
+# Proper installation ##########################################################
+echo "[universal_mailer] Moving bundle to final destination: $target"
+if [[ ! -d "$target" ]]; then
+	mkdir -p "$target" || exit 1
+fi
+mv "$temporarydir/$bundle" "$target/" || exit 1
+################################################################################
+
+# Permissions ##################################################################
+echo "[universal_mailer] Fixing permissions..."
+if [ "$target" == "$homedir" ]; then
+    chown "$USER:staff" "$HOME/Library/Mail"
+    chown -R "$USER:staff" "$homedir"
+fi
+chmod -R 755 "$target"
+################################################################################
+
+# Enable bundles in Mail.app ###################################################
+defaults write "/Library/Preferences/com.apple.mail" EnableBundles -bool YES
+defaults write "/Library/Preferences/com.apple.mail" BundleCompatibilityVersion -int $bundleCompVer
+################################################################################
+
+
+# Add the PluginCompatibilityUUIDs #############################################
+echo "[universal_mailer] Adding PluginCompatibilityUUIDs..."
+plistBundle="$target/$bundle/Contents/Info"
+plistMail="/Applications/Mail.app/Contents/Info"
+plistFramework="/System/Library/Frameworks/Message.framework/Resources/Info"
+
+uuid1=$(defaults read "$plistMail" "PluginCompatibilityUUID")
+uuid2=$(defaults read "$plistFramework" "PluginCompatibilityUUID")
+
+if [[ -n "$uuid1" ]] && ! grep -q $uuid1 "${plistBundle}.plist" ;then
+	defaults write "$plistBundle" "SupportedPluginCompatibilityUUIDs" -array-add "$uuid1"
+fi
+if [[ -n "$uuid2" ]] && ! grep -q $uuid2 "${plistBundle}.plist" ;then
+	defaults write "$plistBundle" "SupportedPluginCompatibilityUUIDs" -array-add "$uuid2"
 fi
 
-#defaults write "$domain" EnableBundles -bool YES
-#defaults write "$domain" BundleCompatibilityVersion -int 3
+plutil -convert xml1 "$plistBundle.plist"
+chmod +r "$plistBundle.plist"
+################################################################################
 
-if [ $macosx_minor_version == "8" ]; then
- for i in $(dscacheutil -q user | grep name | awk '{print $2}' | grep -v "^_"); do
-  if [ -d /Users/$i ]; then
-   if [ -f "/Users/$i/Library/Containers/com.apple.mail/Data/Library/Preferences/com.apple.mail.plist" ]; then
-    echo "changing ownership of com.apple.mail.plist" > /tmp/ulinstaller.log.txt
-    sudo chown $i /Users/$i/Library/Containers/com.apple.mail/Data/Library/Preferences/com.apple.mail.plist
-    defaults write /Users/$i/Library/Containers/com.apple.mail/Data/Library/Preferences/com.apple.mail.plist EnableBundles -bool YES
-    defaults write /Users/$i/Library/Containers/com.apple.mail/Data/Library/Preferences/com.apple.mail.plist BundleCompatibilityVersion -int 3
-    sudo defaults write /Users/$i/Library/Containers/com.apple.mail/Data/Library/Preferences/com.apple.mail.plist EnableBundles -bool YES
-    sudo defaults write /Users/$i/Library/Containers/com.apple.mail/Data/Library/Preferences/com.apple.mail.plist BundleCompatibilityVersion -int 3
-    sudo chown $i /Users/$i/Library/Containers/com.apple.mail/Data/Library/Preferences/com.apple.mail.plist
-   fi
-  fi
- done
-fi
-
-# cleanup
-rm -R /tmp/UM-installation-tmp
-
+exit 0
